In [24]:
import scipy as sp
import numpy as np
from scipy import linalg

In [25]:
array1= np.array(([1,3],[2,4]))
array2= np.array(([5,9],[6,8]))
print(array1, array2)

[[1 3]
 [2 4]] [[5 9]
 [6 8]]


In [26]:
#resolver ecuaciones lineales a*X=b

function1= sp.linalg.solve(array1,array2)
print(function1)
function1 = sp.linalg.inv(array1)
print(function1)

[[-1. -6.]
 [ 2.  5.]]
[[-2.   1.5]
 [ 1.  -0.5]]
