In [1]:
import numpy as np

var1 = np.array([(2,4,6) , (1,3,5)])
var2 = np.array([(2,4,6) , (1,3,5)])

# Funcion exponencial
print(np.exp(var1))
# Funcion logaritmica
print(np.log(var1))





[[  7.3890561   54.59815003 403.42879349]
 [  2.71828183  20.08553692 148.4131591 ]]
[[0.69314718 1.38629436 1.79175947]
 [0.         1.09861229 1.60943791]]
