In [1]:
import numpy as np

var1 = np.array([(2,4,6) , (1,3,5)])
var2 = np.array([(2,4,6) , (1,3,5)])

# Operaciones de matriz
print(var1 + var2)
print(var1 - var2)
print(var1 * var2)
print(var1 / var2)

#



[[ 4  8 12]
 [ 2  6 10]]
[[0 0 0]
 [0 0 0]]
[[ 4 16 36]
 [ 1  9 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
var1 = np.array([(2,4,6) , (1,3,5)])
# Poner todo en una columna
print(var1.ravel())

[2 4 6 1 3 5]


In [3]:
# suma de axes , sumar todos los X , sumar todos los Y
var1 = np.array([(2,4,6) , (1,3,5)])

#suma de columnas Columns
print(var1.sum(axis=0))
#suma de filas  Rows
print(var1.sum(axis=1))

[ 3  7 11]
[12  9]


In [4]:
# raiz de todos los valores
print(np.sqrt(var1))

[[1.41421356 2.         2.44948974]
 [1.         1.73205081 2.23606798]]


In [5]:
# Desviacion estandar
print(np.std(var1))

1.707825127659933
