In [1]:
import numpy as np

# crear un area con numeros autogenerados , con un rango y cuantos numeros quiero (con la misma distancia)
var1 = np.linspace(10,50,40)
print(var1)

[10.         11.02564103 12.05128205 13.07692308 14.1025641  15.12820513
 16.15384615 17.17948718 18.20512821 19.23076923 20.25641026 21.28205128
 22.30769231 23.33333333 24.35897436 25.38461538 26.41025641 27.43589744
 28.46153846 29.48717949 30.51282051 31.53846154 32.56410256 33.58974359
 34.61538462 35.64102564 36.66666667 37.69230769 38.71794872 39.74358974
 40.76923077 41.79487179 42.82051282 43.84615385 44.87179487 45.8974359
 46.92307692 47.94871795 48.97435897 50.        ]


In [2]:
#Funcion para sacar pedasos
var1 = np.array([(2,4,6) , (1,3,5)])
# de linea 0 , quiero elemento numero 2 (osea 1)
print(var1)
print("Operaciones: ")
print(var1[0,1])

#de linea 0 hasta el final , muestra elemento 2
print(var1[0:,1])
print("-------------: ")
var1 = np.array([(2,4,6) , (1,3,5) , (2,4,6) , (1,3,5) , (2,4,6) , (1,3,5)])
print(var1)
print("Operaciones: ")
print(var1[0:,1])
print(var1[1:,1])

print(var1[1:,1:])


[[2 4 6]
 [1 3 5]]
Operaciones: 
4
[4 3]
-------------: 
[[2 4 6]
 [1 3 5]
 [2 4 6]
 [1 3 5]
 [2 4 6]
 [1 3 5]]
Operaciones: 
[4 3 4 3 4 3]
[3 4 3 4 3]
[[3 5]
 [4 6]
 [3 5]
 [4 6]
 [3 5]]


In [3]:
var1 = np.array([(2,4,6) , (1,3,5)])
# Encontrar el maximo y minimo
print(var1.max())
print(var1.min())
# la suma de todo lo de adentro
print(var1.sum())

6
1
21
