In [1]:
import numpy as np

var1 = np.array([(2,3,6), (2,3,6)])
print(var1)

[[2 3 6]
 [2 3 6]]


In [2]:
import numpy as np
var1 = np.array([(2,3,6), (2,3,6)])
var2 = np.array([(2,3,6), (2,3,6)])
print(var1+var2)

[[ 4  6 12]
 [ 4  6 12]]
